FROM debian:latest

ARG USER_ID=1005
ARG USERNAME=flask

WORKDIR /u01
COPY .  /u01

RUN \
  apt-get update -y && \
  apt-get install -y python3 python3-pip && \
  adduser --disabled-password --gecos "" --uid ${USER_ID} ${USERNAME} && \
  pip install --upgrade pip && \
  pip install -r /u01/requirements.txt

EXPOSE 8080

USER ${USERNAME}

ENTRYPOINT [ "gunicorn", "--bind", "0.0.0.0:8080", "wsgi:app" ]
